---
- name: install docker-py workaround
  pip: name=docker-py

- name: start database container
  docker:
    name: "{{ container_name }}"
    image: rmrbest/percona
    state: reloaded
    log_driver: syslog
    detach: true
    ports:
      - "3306:3306"
    volumes:
      - "{{ local_mysql_data_path }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ root_password }}"
      MYSQL_DATABASE: "{{ database_name }}"
      REPLICATION: "{{ active_replication }}" 
      REPLICATION_NODE: "{{ num_node_master }}"
      REPLICATION_SLAVE_USER: "{{ slave_user }}"
      REPLITACION_SLAVE_PASSWORD: "{{ slave_user_password }}"
      
- name: start slave database container
  docker:
    name: "{{ container_name_slave }}"
    image: rmrbest/percona
    state: reloaded 
    log_driver: syslog
    detach: true
    volumes:
      - "{{ local_mysql_data_slave_path }}:/var/lib/mysql"
      - "{{ local_mysql_backup_slave_path }}:/opt/backups"
      - /crons/:/crons/
    env:
      MYSQL_ROOT_PASSWORD: "{{ root_password }}"
      MYSQL_DATABASE: "{{ database_name }}"
      REPLICATION: "{{ active_replication }}" 
      REPLICATION_NODE: "{{ num_node_slave }}"
      REPLICATION_SLAVE_USER: "{{ slave_user }}"
      REPLITACION_SLAVE_PASSWORD: "{{ slave_user_password }}"
    links:
      - "{{ container_name }}:mysql"
