---
- name: install docker-py workaround
  pip: name=docker-py

- name: start database container
  docker:
    name: "{{ container_name }}"
    image: rmrbest/percona
    state: reloaded
    ports:
      - "3306:3306"
    volumes:
      - "{{ local_mysql_data_path }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ root_password }}"
      MYSQL_DATABASE: "{{ database_name }}"
      REPLICATION: "{{ active_replication }}" 
      REPLICATION_NODE: "{{ num_node }}"
      REPLICATION_SLAVE_USER: "{{ slave_user }}"
      REPLITACION_SLAVE_PASSWORD: "{{ slave_user_password }}"
      
